GET http://localhost:3000/tags/health HTTP/1.1

###

GET http://localhost:3000/tags HTTP/1.1

###

GET http://localhost:3000/user/health HTTP/1.1

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "user": {
        "username": "Vahid",
        "email": "akhtarvahid543@gmail.com",
        "password": "12345"
    }
}

###

POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
    "user": {
        "email": "akhtarvahid543@gmail.com",
        "password": "12345"
    }    
}


###  current user

GET http://localhost:3000/users/user HTTP/1.1
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsInVzZXJuYW1lIjoiVmFoaWQiLCJlbWFpbCI6ImFraHRhcnZhaGlkNTQzQGdtYWlsLmNvbSIsImlhdCI6MTcyNzU0OTM4OSwiZXhwIjozNDU1MTAyMzc4fQ.dOpj3uIZQmUSrL2RmR-2q-hHRHR1K_xXhF4tvVteJaY



### update user

PUT http://localhost:3000/users/18
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsInVzZXJuYW1lIjoiVmFoaWQiLCJlbWFpbCI6ImFraHRhcnZhaGlkNTQzQGdtYWlsLmNvbSIsImlhdCI6MTcyNzU0OTM4OSwiZXhwIjozNDU1MTAyMzc4fQ.dOpj3uIZQmUSrL2RmR-2q-hHRHR1K_xXhF4tvVteJaY

{
    "user": {
        "username": "Vahid Akhtar",
        "email": "akhtarvahid543@gmail.com",
        "password": "12345"
    }
}


### Delete user
DELETE http://localhost:3000/users/22
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInVzZXJuYW1lIjoiVmFoaWQiLCJlbWFpbCI6ImFraHRhcnZhaGlkNTQzQGdtYWlsLmNvbSIsImlhdCI6MTcyNzU5MTQ3OSwiZXhwIjozNDU1MTg2NTU4fQ.FdgNYffrZCYxXZubftkY7GYUqeh4Hrs-M3KgTnHhpyQ

### Story API list

### health 

GET http://localhost:3000/story/health HTTP/1.1

### create story

POST http://localhost:3000/story HTTP/1.1
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJWYWhpZCIsImVtYWlsIjoiYWtodGFydmFoaWQ1NDNAZ21haWwuY29tIiwiaWF0IjoxNzI3NjIxOTE4LCJleHAiOjM0NTUyNDc0MzZ9.Uxy8ZlQmEmzdTxkY6Z9F_pyCJRZRfh9NEfCfhT5bAFY

{
    "story": {
        "title": "My story 1",
        "description": "Lets buy a story 2",
        "body": "This is my first story on the blogging platform",
        "tagList": ["react", "js"]
    }
}

### get by slug 

GET http://localhost:3000/story/story-2-hn87zh HTTP/1.1


### Update story by id

PUT http://localhost:3000/story/3
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJWYWhpZCIsImVtYWlsIjoiYWtodGFydmFoaWQ1NDNAZ21haWwuY29tIiwiaWF0IjoxNzI3NzIwMDIxLCJleHAiOjM0NTU0NDM2NDJ9.m-zYX3A7S-5Tpcyhto1L4e0fyCinNFtlSj3631da9ow

{
    "story": {
        "title": "Newly Updated story 1",
        "description": "Lets buy a story 2",
        "tagList": ["nodejs", "js"]
    }
}

### Delete story by id

DELETE  http://localhost:3000/story/2
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJWYWhpZCIsImVtYWlsIjoiYWtodGFydmFoaWQ1NDNAZ21haWwuY29tIiwiaWF0IjoxNzI3NzIwMDIxLCJleHAiOjM0NTU0NDM2NDJ9.m-zYX3A7S-5Tpcyhto1L4e0fyCinNFtlSj3631da9ow


### Find all stories(unprotected)

GET http://localhost:3000/story/all

### Find all stories filter by tag=java
GET http://localhost:3000/story/all?tag=java

### Find all stories filter by author=vahid
GET http://localhost:3000/story/all?author=vahid

### Find all stories using filter, limit, and offset.
GET http://localhost:3000/story/all?author=vahid&limit=2&offset=2

### Find all stories filter by limit and offset
GET http://localhost:3000/story/all?limit=2&offset=4

### Find all stories filter by favorite username(ex. favorite=Akhtar)
GET http://localhost:3000/story/all?favorited=Akhtar

### Add favorite story to user and increase count of favoritesCount
POST http://localhost:3000/story/sass-blog-153v0d/favorite
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJWYWhpZCIsImVtYWlsIjoiYWtodGFydmFoaWQ1NDNAZ21haWwuY29tIiwiaWF0IjoxNzI3NzIwMDIxLCJleHAiOjM0NTU0NDM2NDJ9.m-zYX3A7S-5Tpcyhto1L4e0fyCinNFtlSj3631da9ow


### Remove favorite story from user and decrease count of favoritesCount
DELETE http://localhost:3000/story/sass-blog-153v0d/favorite
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJWYWhpZCIsImVtYWlsIjoiYWtodGFydmFoaWQ1NDNAZ21haWwuY29tIiwiaWF0IjoxNzI3NzIwMDIxLCJleHAiOjM0NTU0NDM2NDJ9.m-zYX3A7S-5Tpcyhto1L4e0fyCinNFtlSj3631da9ow


### Profile API's
GET http://localhost:3000/profiles/health HTTP/1.1

### get profile
GET http://localhost:3000/profiles/Akhtar
content-type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJWYWhpZCIsImVtYWlsIjoiYWtodGFydmFoaWQ1NDNAZ21haWwuY29tIiwiaWF0IjoxNzI3NzIwMDIxLCJleHAiOjM0NTU0NDM2NDJ9.m-zYX3A7S-5Tpcyhto1L4e0fyCinNFtlSj3631da9ow

### follow profile api
POST http://localhost:3000/profiles/Akhtar/follow
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhbmFoaWQiLCJlbWFpbCI6ImFuYWhpZEBnbWFpbC5jb20iLCJpYXQiOjE3Mjc5NjQ0MDksImV4cCI6MzQ1NTkzMjQxOH0.fn7Xz9900c1gQ2jzh3ns2unHOZEpuGDkRGsOZxA-8zY

### unfollow profile api
DELETE http://localhost:3000/profiles/Akhtar/unfollow
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhbmFoaWQiLCJlbWFpbCI6ImFuYWhpZEBnbWFpbC5jb20iLCJpYXQiOjE3Mjc5NjQ0MDksImV4cCI6MzQ1NTkzMjQxOH0.fn7Xz9900c1gQ2jzh3ns2unHOZEpuGDkRGsOZxA-8zY