name: substack-container #  docker container group name
services:
  nestjs_api: # 1 - nest application service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: 
      - .env.stage.dev  
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres_db #  postgres_db - dependent on line 22(postgres_db service: name should be same at both places)

  postgres_db: # 2 - database service
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
