name: substack-container #  docker container group name
services:
  nestjs_api: # 1 - nest application service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=postgres_db # service name as the host
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres_db #  postgres_db - dependent on line 22(postgres_db service: name should be same at both places)

  postgres_db: # 2 - database service
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
